language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    - os:   linux
      env:  TARGET=kernel DISTRO=ubuntu@19.04 SUBARCH=ppc64le DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"

install:
  - docker pull linuxppc/build:$DISTRO-$(uname -m)

script:
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
