language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    - os:   linux
      arch: ppc64le
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-19.10 DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - id
  - ls -ld $HOME/.ccache
  - mkdir $HOME/.ccache/tmp
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
