language: c
dist: xenial
sudo: required
services: docker
cache: ccache

branches:
  only:
    - ci-test
    - fixes-test
    - next-test

matrix:
  include:
    # 64-bit configs
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64le DEFCONFIG=ppc64le_allmodconfig	# PPC_BOOK3S_64 && LITTLE_ENDIAN
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=allmodconfig		# PPC_BOOK3S_64 && BIG_ENDIAN
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=ppc64_book3e_allmodconfig	# PPC_BOOK3E_64
    # 32-bit configs
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=ppc32_allmodconfig		# PPC_BOOK3S_32
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=ppc40x_defconfig		# PPC_40x
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=ppc44x_defconfig		# PPC_44x
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=mpc885_ads_defconfig	# PPC_8xx
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=kernel@ppc64 DEFCONFIG=corenet32_smp_defconfig	# PPC_85xx
    # selftests
    - os:  linux-ppc64le
      env: IMAGE=ubuntu@18.10 TARGET=ppctests@ppc64le
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=ppctests@ppc64
    - os:  linux-ppc64le
      env: IMAGE=ubuntu@18.10 TARGET=selftests@ppc64le
    - os:  linux
      env: IMAGE=ubuntu@18.10 TARGET=selftests@ppc64

script:
  - git clone -q --depth 1 https://github.com/mpe/ci-scripts.git
  - mkdir -p build
  - bash -c "docker pull mpee/linuxppc-build:$IMAGE"
  - make -C ci-scripts/build KBUILD_BUILD_TIMESTAMP=$(date +%Y-%m-%d) CCACHE=$HOME/.ccache CI_OUTPUT=$PWD/build JFACTOR=$(nproc) SRC=$PWD ${TARGET}@$IMAGE
