language: c
dist: xenial
cache: ccache

env:
  global:
    - ARCH=powerpc
    - KBUILD_OUTPUT=$TRAVIS_BUILD_DIR/build

matrix:
  include:
    - os:  linux-ppc64le
      env: DEFCONFIG=ppc64le_defconfig

branches:
  only:
    - ci-test
    - fixes-test
    - next-test

script:
  - mkdir -p $KBUILD_OUTPUT
  - make $DEFCONFIG
  - travis_wait 50 make -s -j $(nproc)
