language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-19.04 DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux-ppc64le
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-19.04 DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le (native) (PPC_BOOK3S_64 && LITTLE_ENDIAN)"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
