language: c
dist: xenial
sudo: required
services: docker
cache: ccache

branches:
  only:
    - ci-test
    - fixes-test
    - next-test

matrix:
  include:
    # 64-bit configs
    - os:  linux
      env: BUILD_ENV=ppc64le@ubuntu@18.10 TARGET=kernel DEFCONFIG=ppc64le_defconfig	# PPC_BOOK3S_64 && LITTLE_ENDIAN

script:
  - id
  - git clone -q --depth 1 https://github.com/mpe/ci-scripts.git $HOME/ci-scripts
  - mkdir -p $HOME/output
  - make -C ~/ci-scripts/build pull-image@$BUILD_ENV
  - make -C ~/ci-scripts/build KBUILD_BUILD_TIMESTAMP=$(date +%Y-%m-%d) CCACHE=$HOME/.ccache CI_OUTPUT=$HOME/output JFACTOR=$(nproc) SRC=$PWD $TARGET@$BUILD_ENV
