language: c
dist: xenial
cache: ccache

env:
  global:
    - ARCH=powerpc
    - KBUILD_OUTPUT=$TRAVIS_BUILD_DIR/build
    - KBUILD_BUILD_TIMESTAMP=$(date +%Y-%m-%d)
    - CCACHE=$HOME/.ccache

matrix:
  include:
    - os:  linux-ppc64le
      env: DEFCONFIG=ppc64le_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-"
    - os:  linux-ppc64le
      env: DEFCONFIG=skiroot_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-"
    - os:  linux
      env: DEFCONFIG=ppc64_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
    - os:  linux
      env: DEFCONFIG=pmac32_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu

branches:
  only:
    - ci-test
    - fixes-test
    - next-test

script:
  - mkdir -p $KBUILD_OUTPUT
  - make $DEFCONFIG
  - travis_wait 50 make -s -j $(nproc)
  - ccache -s
