language: c
dist: xenial
cache: ccache

env:
  global:
    - ARCH=powerpc
    - KBUILD_OUTPUT=$TRAVIS_BUILD_DIR/build
    - KBUILD_BUILD_TIMESTAMP=$(date +%Y-%m-%d)
    - CCACHE=$HOME/.ccache

matrix:
  include:
    - os:   linux-ppc64le
      env:  DEFCONFIG=ppc64le_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-"
      name: "kernel(ppc64le) (native)"
    - os:   linux
      env:  DEFCONFIG=ppc64le_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-"
      name: "kernel(ppc64le)"
      addons:
        apt:
          packages:
          - gcc-powerpc64le-linux-gnu
    - os:   linux-ppc64le
      env:  DEFCONFIG=skiroot_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-"
      name: "kernel(skiroot)"
    - os:   linux
      env:  DEFCONFIG=ppc64_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-"
      name: "kernel(ppc64)"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
    - os:  linux
      env: DEFCONFIG=pmac32_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-"
      name: "kernel(pmac32)"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
    - os:  linux
      env: DEFCONFIG=ppc64e_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-"
      name: "kernel(ppc64e)"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
          - u-boot-tools
    - os:  linux-ppc64le
      env:  DEFCONFIG=ppc64le_defconfig CROSS_COMPILE="ccache powerpc64le-linux-gnu-" SELFTESTS=1
      name: "selftests(ppc64le)"
      addons:
        apt:
          packages:
          - libcap-dev
          - libcap-ng-dev
          - libnuma-dev
          - libpopt-dev
    - os:  linux
      env:  DEFCONFIG=ppc64_defconfig CROSS_COMPILE="ccache powerpc-linux-gnu-" SELFTESTS=1
      name: "selftests(ppc64)"
      addons:
        apt:
          packages:
          - gcc-powerpc-linux-gnu
          - gcc-5-multilib-powerpc-linux-gnu

branches:
  only:
    - ci-test
    - fixes-test
    - next-test

script:
  - mkdir -p $KBUILD_OUTPUT
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
  - ccache -s
